# Generated by Django 4.0.5 on 2022-06-10 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GolfClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=128)),
                ('_streetHouseNumber', models.CharField(blank=True, max_length=128, null=True)),
                ('_zip', models.CharField(blank=True, max_length=24, null=True)),
                ('_city', models.CharField(blank=True, max_length=128, null=True)),
                ('_website', models.URLField(blank=True, max_length=64, null=True)),
                ('_email', models.EmailField(blank=True, max_length=128, null=True)),
                ('_phoneNumber', models.CharField(blank=True, max_length=32, null=True)),
                ('_imageUrl', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GolfCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=128)),
                ('_holesAmount', models.IntegerField()),
                ('_golfClub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.golfclub')),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_courseNameIdentifier', models.CharField(blank=True, max_length=128, null=True)),
                ('_holeNumber', models.IntegerField()),
                ('_par', models.IntegerField()),
                ('_distance', models.IntegerField()),
                ('_hcp', models.IntegerField(blank=True, null=True)),
                ('_golfCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.golfcourse')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_firstName', models.CharField(max_length=48)),
                ('_lastName', models.CharField(max_length=48)),
                ('_email', models.EmailField(blank=True, max_length=128, null=True)),
                ('_password', models.CharField(max_length=128)),
                ('_handicap', models.IntegerField()),
                ('_phoneNumber', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserHoleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_score', models.IntegerField()),
                ('_hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hole')),
                ('_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
