# Generated by Django 4.0.5 on 2022-06-10 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GolfClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=128)),
                ('_streetHouseNumber', models.CharField(max_length=128)),
                ('_zip', models.CharField(max_length=24)),
                ('_city', models.CharField(max_length=128)),
                ('_website', models.CharField(max_length=64)),
                ('_email', models.CharField(max_length=128)),
                ('_phoneNumber', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GolfCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=128)),
                ('_holeAmount', models.IntegerField()),
                ('_golfClub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.golfclub')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_firstName', models.CharField(max_length=48)),
                ('_lastName', models.CharField(max_length=48)),
                ('_streetHouseNr', models.CharField(max_length=128)),
                ('_handicap', models.IntegerField()),
                ('_phoneNumber', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_hole_number', models.IntegerField()),
                ('_par', models.IntegerField()),
                ('_distance', models.IntegerField()),
                ('_hcp', models.IntegerField()),
                ('_golfCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.golfcourse')),
            ],
        ),
    ]
