# Generated by Django 4.0.5 on 2022-06-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userholescore',
            name='_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
