# Generated by Django 4.0.5 on 2022-06-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfcourse',
            name='_holeAmount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hole',
            name='_distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hole',
            name='_hcp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hole',
            name='_hole_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hole',
            name='_par',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='_handicap',
            field=models.IntegerField(),
        ),
    ]
