# Generated by Django 4.0.5 on 2022-06-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_golfcourse__holeamount_alter_hole__distance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hole',
            old_name='_hole_number',
            new_name='_holeNumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_streetHouseNr',
        ),
    ]
