# Generated by Django 4.0.5 on 2022-06-10 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename__hole_number_hole__holenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHoleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hole')),
                ('_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
