# Generated by Django 4.0.5 on 2022-06-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userholescore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfcourse',
            name='_holeAmount',
        ),
        migrations.AddField(
            model_name='userholescore',
            name='_score',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
