# Generated by Django 4.0.5 on 2022-06-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_golfcourse__holeamount_userholescore__score'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcourse',
            name='_holesAmount',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
