# Generated by Django 4.0.5 on 2022-06-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_golfcourse__holesamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='_courseNameIdentifier',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
